### ISSUE TITLE
Open Meta trows errors (latest 1.0.4 version), Log in comment.

### ISSUE THREAD

**Issue by Tinuz97** [drinfernoo/repository.openmeta#2]
Library import does work now with the fix,but i am seeing regulary a open meta pop-up error in kodi (18.1 RC) 

2019-02-17 13:59:09.931 T:12988   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.HTTPError'>
                                            Error Contents: 500 Server Error: Internal Server Error for url: https://api.trakt.tv/sync/collection/movies?extended=full
                                            Traceback (most recent call last):
                                              File "C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.openmeta\service.py", line 27, in <module>
                                                update_library()
                                              File "C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.openmeta\addon.py", line 37, in update_library
                                                lib_movies.sync_trakt_collection()
                                              File "C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\lib_movies.py", line 20, in sync_trakt_collection
                                                nav_movies.lists_trakt_movies_collection_to_library()
                                              File "C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\nav_movies.py", line 590, in lists_trakt_movies_collection_to_library
                                                movies_add_all_to_library(Trakt.get_collection('movies'))
                                              File "C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\Trakt.py", line 166, in get_collection
                                                return call_trakt('sync/collection/%s?extended=full' % type)
                                              File "C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\Trakt.py", line 62, in call_trakt
                                                response.raise_for_status()
                                              File "C:\Users\USER\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 939, in raise_for_status
                                                raise HTTPError(http_error_msg, response=self)
                                            HTTPError: 500 Server Error: Internal Server Error for url: https://api.trakt.tv/sync/collection/movies?extended=full
                                            -->End of Python script error report<--
2019-02-17 13:59:23.317 T:13144   ERROR: XFILE::CDirectory::GetDirectory - Error getting
2019-02-17 13:59:28.363 T:10068   ERROR: Unable to find plugin
2019-02-17 13:59:28.363 T:10068   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://
2019-02-17 13:59:28.364 T:11776   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
2019-02-17 14:00:23.507 T:572  NOTICE: VideoInfoScanner: Starting scan ..
2019-02-17 14:00:23.507 T:572 WARNING: VIDEO::CVideoInfoScanner::Process directory 'special://profile/addon_data/plugin.video.openmeta/Movies/' does not exist - skipping scan.
2019-02-17 14:00:23.856 T:572 WARNING: ADDON::CScraper::NfoUrl: scraper returned multiple results; using first
2019-02-17 14:00:26.378 T:572   ERROR: CCurlFile::Open failed with code 404 for https://api.thetvdb.com/series/121361/images/query?keyType=fanart:
2019-02-17 14:00:26.378 T:572   ERROR: ADDON::CScraper::Run: Unable to parse web site
2019-02-17 14:00:26.943 T:572   ERROR: CCurlFile::Open failed with code 404 for https://api.thetvdb.com/series/121361/images/query?keyType=seasonwide:
2019-02-17 14:00:26.943 T:572   ERROR: ADDON::CScraper::Run: Unable to parse web site
2019-02-17 14:02:16.210 T:572 WARNING: ADDON::CScraper::NfoUrl: scraper returned multiple results; using first
2019-02-17 14:02:17.879 T:572   ERROR: CCurlFile::Open failed with code 404 for https://api.thetvdb.com/series/247897/images/query?keyType=fanart:
2019-02-17 14:02:17.879 T:572   ERROR: ADDON::CScraper::Run: Unable to parse web site
2019-02-17 14:02:18.162 T:572   ERROR: CCurlFile::Open failed with code 404 for https://api.thetvdb.com/series/247897/images/query?keyType=poster:
2019-02-17 14:02:18.162 T:572   ERROR: ADDON::CScraper::Run: Unable to parse web site
2019-02-17 14:02:18.335 T:572   ERROR: CCurlFile::Open failed with code 404 for https://api.thetvdb.com/series/247897/images/query?keyType=season:
2019-02-17 14:02:18.335 T:572   ERROR: ADDON::CScraper::Run: Unable to parse web site
2019-02-17 14:02:18.680 T:572   ERROR: CCurlFile::Open failed with code 404 for https://api.thetvdb.com/series/247897/images/query?keyType=series:
2019-02-17 14:02:18.680 T:572   ERROR: ADDON::CScraper::Run: Unable to parse web site
2019-02-17 14:02:55.964 T:11776  NOTICE: stop player
2019-02-17 14:02:55.964 T:11776  NOTICE: Storing total System Uptime
2019-02-17 14:02:55.964 T:11776  NOTICE: Saving settings
2019-02-17 14:02:55.972 T:11776  NOTICE: Saving skin settings
2019-02-17 14:02:55.979 T:11776  NOTICE: stop all

**Comment by drinfernoo** [comment]
That appears to be an issue with the Trakt servers, rather than a problem with OpenMeta. Try the most recent version, but I'm closing this one for now.
